# Generated by Django 3.2.12 on 2024-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='common_news',
            field=models.BooleanField(default=False),
        ),
    ]
