# Generated by Django 3.2.12 on 2024-04-14 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0031_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField(verbose_name='Порядок отображения')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок новости')),
                ('text', models.TextField(max_length=400, verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Фото')),
                ('connection', models.BooleanField(default=False, verbose_name='Нужна ссылка на подопечного?')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Подопечный, на которого даётся ссылка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
