# Generated by Django 3.2.12 on 2024-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_send_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_images', verbose_name='Фото*'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='текст ссылки на картинку'),
        ),
        migrations.AlterField(
            model_name='news',
            name='index_number',
            field=models.IntegerField(verbose_name='Порядок отображения*'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(max_length=400, verbose_name='Текст новости*'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок новости*'),
        ),
    ]
