# Generated by Django 3.2.12 on 2024-01-18 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pethistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethistory',
            name='node',
            field=models.TextField(verbose_name='Новость из жизни подопечного'),
        ),
        migrations.AlterField(
            model_name='pethistory',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Кличка подопечного'),
        ),
        migrations.AlterField(
            model_name='pethistory',
            name='time',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
