# Generated by Django 3.2.12 on 2024-01-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20240118_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pethistory',
            options={'verbose_name': 'Истории подопечных', 'verbose_name_plural': 'Истории подопечных'},
        ),
    ]
