# Generated by Django 3.2.12 on 2024-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pethistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petstatus',
            options={'verbose_name': 'Статус подопечного', 'verbose_name_plural': 'Статусы подопечных'},
        ),
    ]
