# Generated by Django 3.2.12 on 2024-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_alter_pet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='needs',
            field=models.TextField(null=True, verbose_name='Нужды в настоящий момент'),
        ),
    ]
