# Generated by Django 3.2.12 on 2024-01-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_pet_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index_number', models.IntegerField(verbose_name='Порядок отображения')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='news_images', verbose_name='Фото')),
                ('connection', models.BooleanField(default=False, verbose_name='Нужна ссылка на подопечного?')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Подопечный, на которого даётся ссылка')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
