# Generated by Django 3.2.12 on 2024-01-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_alter_news_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Index_number',
            new_name='index_number',
        ),
    ]
