# Generated by Django 3.2.12 on 2024-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_auto_20240201_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='Фото животного'),
        ),
    ]
