# Generated by Django 3.2.12 on 2024-03-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0018_petimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetImage',
        ),
    ]
