# Generated by Django 3.2.12 on 2024-03-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0019_delete_petimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='Фото животного')),
                ('index_number', models.IntegerField(verbose_name='Порядок отображения')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Кличка подопечного')),
            ],
            options={
                'verbose_name': 'Фотография подопечного',
                'verbose_name_plural': 'Фотогафии подопечных',
            },
        ),
    ]
