# Generated by Django 3.2.12 on 2024-03-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_auto_20240309_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images', verbose_name='Фото животного'),
        ),
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(upload_to='pet_images', verbose_name='Фото животного'),
        ),
    ]
