# Generated by Django 3.2.12 on 2024-03-24 19:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_alter_requestforguardianship_other_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforguardianship',
            name='other_pets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('no pet', 'нет животных'), ('cat', 'кошка'), ('dog', 'собака'), ('rabbit', 'кролик'), ('others', 'другие')], max_length=50), size=None, verbose_name='Если у вас уже есть питомцы, укажите, какие:'),
        ),
    ]
