# Generated by Django 3.2.12 on 2024-03-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0025_alter_requestforguardianship_other_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.CharField(max_length=20, verbose_name='Вид животного')),
            ],
        ),
        migrations.RemoveField(
            model_name='requestforguardianship',
            name='other_pets',
        ),
        migrations.AddField(
            model_name='requestforguardianship',
            name='other_pets',
            field=models.ManyToManyField(to='pets.OtherPets', verbose_name='Если у вас уже есть питомцы, укажите, какие:'),
        ),
    ]
