# Generated by Django 3.2.12 on 2024-04-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0028_petscategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petscategory',
            name='image',
        ),
    ]
