# Generated by Django 3.2.12 on 2024-04-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0032_pethistory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pethistory',
            name='title',
            field=models.CharField(default='Новое событие в жизни None', max_length=60, verbose_name='Заголовок новости'),
        ),
    ]
