# Generated by Django 3.2.12 on 2024-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0034_auto_20240415_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='pethistory',
            name='send_news',
            field=models.BooleanField(default=False, verbose_name='Отправить в почтовую рассылку'),
        ),
    ]
