# Generated by Django 3.2.12 on 2024-04-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0037_alter_pethistory_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherPets',
            new_name='OtherPet',
        ),
    ]
