# Generated by Django 3.2.12 on 2024-05-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0038_rename_otherpets_otherpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
